# Generated by Django 4.2 on 2023-12-17 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_alter_weekday_sort_order"),
        ("university", "0004_alter_intakestream_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="module",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="week_day",
        ),
        migrations.AddField(
            model_name="timetable",
            name="semester",
            field=models.CharField(
                choices=[("1", "Sem 1"), ("2", "Sem 2")],
                default="1",
                help_text="Each academic year has a maximum of 2 semesters, defaults to 1",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=145)),
                ("start_time", models.TimeField(default=django.utils.timezone.now)),
                ("end_time", models.TimeField()),
                (
                    "lecturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="university.lecturer",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="university.module",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="university.timetable",
                    ),
                ),
                (
                    "week_day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.weekday",
                    ),
                ),
            ],
        ),
    ]
