# Generated by Django 4.2 on 2023-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "university",
            "0005_remove_timetable_lecturer_remove_timetable_module_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="title",
            field=models.CharField(default="", editable=False, max_length=255),
        ),
    ]
