# Generated by Django 4.2 on 2023-12-18 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0006_timetable_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="session",
            unique_together={("timetable", "lecturer", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("semester", "intake_stream", "academic_year")},
        ),
    ]
