# Generated by Django 5.0 on 2023-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8, unique=True)),
                ("sort_order", models.IntegerField(default=0, unique=True)),
            ],
            options={
                "db_table": "general_week_day",
                "ordering": ["sort_order"],
            },
        ),
    ]
