# Generated by Django 4.2 on 2023-12-17 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekday",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Lowest is 0 and highest should be 6",
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
