# Generated by Django 4.2 on 2023-12-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_alter_weekday_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekday",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
